"""initial schema

Revision ID: 81bb3bf5563d
Revises:
Create Date: 2026-08-09 21:47:07.077351

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81bb3bf5563d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Trigram matching powers the "did you mean 19181?" fallback when an exact
    # bib search finds nothing (OCR reads a 6 as an 8, or drops a digit).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_is_published"), "events", ["is_published"], unique=False)
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=True)
    op.create_table(
        "photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key_original", sa.String(length=500), nullable=False),
        sa.Column("storage_key_preview", sa.String(length=500), nullable=False),
        sa.Column("storage_key_thumb", sa.String(length=500), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "sha256", name="uq_photos_event_sha256"),
    )
    op.create_index(op.f("ix_photos_event_id"), "photos", ["event_id"], unique=False)
    op.create_table(
        "photo_bibs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("bib_number", sa.String(length=16), nullable=False),
        sa.Column("is_uncertain", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("photo_id", "bib_number", name="uq_photo_bibs_photo_number"),
    )
    op.create_index(
        "ix_photo_bibs_event_bib", "photo_bibs", ["event_id", "bib_number"], unique=False
    )
    op.create_index(op.f("ix_photo_bibs_photo_id"), "photo_bibs", ["photo_id"], unique=False)
    # ### end Alembic commands ###

    # GIN + trigram ops: backs repositories.photos.search_similar_bibs().
    op.execute(
        "CREATE INDEX ix_photo_bibs_number_trgm ON photo_bibs USING gin (bib_number gin_trgm_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_photo_bibs_number_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photo_bibs_photo_id"), table_name="photo_bibs")
    op.drop_index("ix_photo_bibs_event_bib", table_name="photo_bibs")
    op.drop_table("photo_bibs")
    op.drop_index(op.f("ix_photos_event_id"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.drop_index(op.f("ix_events_is_published"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
